### ISSUE TITLE
Change in versioning scheme

### ISSUE THREAD

**Issue by zakkak** [graalvm/labs-openjdk#1]
Starting with labsjdk 22 the version scheme no longer includes the old jvmci/Graal version (22+13-jvmci-b01 vs 21+35-jvmci-**23.1**-b15):

```
❯ ~/jvms/labsjdk-ce-latest-22+13-jvmci-b01/bin/java -version 
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+13-jvmci-b01)
OpenJDK 64-Bit Server VM (build 22+13-jvmci-b01, mixed mode, sharing)

❯ ~/jvms/labsjdk-ce-21-jvmci-23.1-b15/bin/java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

Is the removal of the jvmci/graal version intentional? 
This change results in [Quarkus failing to parse GraalVM version starting with GraalVM for JDK 22](https://github.com/quarkusio/quarkus/issues/36246) 

cc @gilles-duboscq @dougxc @jerboaa

**Comment by dougxc** [comment]
Yes, it is intentional. The JVMCI version is now simply a Java version but with an extra JVMCI-specific build number. (cc @zapster )

**Comment by zapster** [comment]
For reference, the new version scheme was adopted in graal by https://github.com/oracle/graal/pull/7411, that is the PR that first introduced labsjdk 22.
